### ISSUE TITLE
Not able to create Blur effect 

### ISSUE THREAD

**Issue by SoloDuo** [KollegDev/KollegHP#7]
I am not able to create a Blur effect for the pic.

How it should look like:
![PerfectResult](https://user-images.githubusercontent.com/46689117/112159594-a366db80-8be9-11eb-9bf2-6a2c5c7719fb.PNG)

My bad work:
![NotGood](https://user-images.githubusercontent.com/46689117/112159655-afeb3400-8be9-11eb-81ff-de82a620f766.PNG)

Code:
`
      
      <div class="row-span-2 ">
        <a href="projectDescription.html"><img
          style="
          background: rgba(241, 237, 237, 0.1);
          box-shadow: 0 8px 32px 0 rgba(218, 218, 224, 0.37);
          backdrop-filter: blur( 20.0px );
          "
           class="object-cover w-full h-96 rounded-t-2xl "
            src="" alt="" /></a>
        <div style="border-radius: 0px 0px 25px 25px;
              background: rgba(255, 255, 255, 0.1);
              box-shadow: inset 0px 7px 12px rgba(0, 0, 0, 0.25);
              backdrop-filter: blur(60.844px);
              border-radius: 0px 0px 25px 25px;" 
              class="p-2 shadow-2xl rounded-b-2xl">
          <h1 class="font-bold">Card one</h1>
          <h2>Sed ut perspiciatis unde omnis iste natus error sit.</h2>
        </div>
      </div>`

**Comment by ScratchyDot** [comment]
![image](https://user-images.githubusercontent.com/80162687/112187097-0fedd480-8c02-11eb-8f4b-27e18d64dec0.png)

If you are currently developing on Firefox, it is only possible to enable this effect over the about:config
As of right now, it is not enabled by default.
